name: Check PR

on:
  push:
    branches: [ main ]

env:
  PROJECT_FILE: newApp.xcodeproj
  PROJECT_SCHEME: newApp

jobs: #3
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
