name: Check PR

on:
  push:
    branches: [ main ]

env:
  PROJECT_FILE: newApp.xcodeproj
  PROJECT_SCHEME: newApp

jobs:  
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2.0'
    - name: Xcode Test
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
       project: newApp.xcodeproj
       scheme: newApp
       destination: platform:iOS Simulator, id:5ECC5280-9D70-4DA9-AF79-40AAF0546AE4, OS:16.2, name:iPhone 11 Pro Max
       action: test
