name: CICD Demo
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
 build-and-test:
  runs-on: macos-latest
  steps:
  - uses: actions/checkout@v2
  - name: Xcode Test
    uses: devbotsxyz/xcode-test@v1.1.0
    with:
        xcode-version: latest
        workspace: 'testCIcd.xcodeproj/project.xcworkspace' # `project` and `workspace` cannot be used at the same time
        scheme: 'newApp'
        configuration: Debug
        destination: platform=iOS Simulator,OS=latest,name=iPhone 11
