name: Check PR

on:
  push:
    branches: [ main ]

env:
  PROJECT_FILE: newApp.xcodeproj
  PROJECT_SCHEME: newApp

jobs:  
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
