name: Check PR

on:
  push:
    branches: [ main ]

env:
  PROJECT_FILE: newApp.xcodeproj
  PROJECT_SCHEME: newApp

jobs:  
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode.version }}

    - name: Xcode Test
      uses: devbotsxyz/xcode-test@v1.1.0
      with:
        project: ${{ env.PROJECT_FILE }}
        scheme: ${{ env.PROJECT_SCHEME }}
        configuration: Debug
        destination: ${{ matrix.xcode.destination }}

    - uses: codecov/codecov-action@v1
      name: Determine code coverage with CodeCov

    - name: Sed new version in Podspec
      run: sed -i "" -e 's|<LIB_VERSION>|1.1.1|g' RFIBAN-Helper.podspec

    - name: Perform Cocoapod lib lint validation
      run: make validate
