name: Check PR

on:
  push:
    branches: [ main ]

env:
  PROJECT_FILE: newApp.xcodeproj
  PROJECT_SCHEME: newApp

jobs:  
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2.0'
    - name: Xcode Test
      uses: devbotsxyz/xcode-test@v1.1.0
      with:
        project: ${{ env.PROJECT_FILE }}
        scheme: ${{ env.PROJECT_SCHEME }}
        configuration: Debug
        destination: platform=iOS Simulator,OS=latest,name=iPhone 11
